config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'

  get 'about' => 'about#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "books#index"
  
   resources :books
   resources :authors
   resources :categories
   resources :publishers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  @page_title = 'About Us' ;
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def          show
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>This is the About us page </p>
<p>THis is the titile page I want it in the frent end </p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id= "books-index">
  <div class="row">
        <div class="col-md-3 col-sm-3">
          <h3>Ruby on Rails Power</h3>
          <%= image_tag('ruby_on_rails_power.jpg') %>
          <%= link_to 'Read More' ,book_path(1), class:"btn btn-primary"%>
        </div>
        <div class="col-md-3 col-sm-3">
         <h3>Ruby on Rails Power</h3>
          <%= image_tag('ruby_on_rails_power.jpg') %>
          <%= link_to 'Read More' ,book_path(2), class:"btn btn-primary"%>
        </div>
        <div class="col-md-3 col-sm-3">
         <h3>Ruby on Rails Power</h3>
          <%= image_tag('ruby_on_rails_power.jpg') %>
          <%= link_to 'Read More' ,book_path(3), class:"btn btn-primary"%>
        </div>
        <div class="col-md-3 col-sm-3">
        <h3>Ruby on Rails Power</h3>
          <%= image_tag('ruby_on_rails_power.jpg') %>
          <%= link_to 'Read More' ,book_path(4), class:"btn btn-primary"%>
        </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-sm-3">
      <h3>Ruby on Rails Power</h3>
      <%= image_tag('ruby_on_rails_power.jpg') %>
      <%= link_to 'Read More' ,book_path(5), class:"btn btn-primary"%>
    </div>
    <div class="col-md-3 col-sm-3">
      <h3>Ruby on Rails Power</h3>
      <%= image_tag('ruby_on_rails_power.jpg') %>
      <%= link_to 'Read More' ,book_path(6), class:"btn btn-primary"%>
    </div>
    <div class="col-md-3 col-sm-3">
      <h3>Ruby on Rails Power</h3>
      <%= image_tag('ruby_on_rails_power.jpg') %>
      <%= link_to 'Read More' ,book_path(7), class:"btn btn-primary"%>
    </div>
    <div class="col-md-3 col-sm-3">
      <h3>Ruby on Rails Power</h3>
      <%= image_tag('ruby_on_rails_power.jpg') %>
      <%= link_to 'Read More' ,book_path(8), class:"btn btn-primary"%>
    </div>
  </div>
  
</div>

app/views/books/new.html.erb
<h2>
  Add new Book
</h2>

<%= form_for @book do |f|%>
   <div class="form-group">
     <%= f.label :title %><br />
     <%= f.text_field :title , class:'form-control'%><br />
   </div>
   <div class="form-group">
     <%= f.label :isbn %><br />
     <%= f.text_field :isbn , class:'form-control'%><br />
   </div>
    <div class="form-group">
     <%= f.label :category %><br />
     <%= f.select :category_id, options_for_select(Category.all.pluck(:name, :id), include_blank: 'Select One'), { class: 'form-control' } %><br /><br />
   </div>

   <div class="form-group">
     <%= f.label :authour %><br />
     <%= f.select :authour_id, options_for_select(Category.all.pluck(:name, :id), include_blank: 'Select One'), { class: 'form-control' } %><br /><br />
   </div>
   <div class="form-group">
     <%= f.label :Publisher %><br />
     <%= f.select :Publisher_id, options_for_select(Category.all.pluck(:name, :id), include_blank: 'Select One'), { class: 'form-control' } %><br /><br />
   </div>
    <div class="form-group">
     <%= f.label :formate %><br />
     <%= f.text_field :formate , class:'form-control'%><br />
    </div>
     <div class="form-group">
     <%= f.label :excerpt %><br />
     <%= f.text_area :excerpt , class:'form-control'%><br />
    </div>
     <div class="form-group">
     <%= f.label :pages %><br />
     <%= f.number_field :pages , class:'form-control'%><br />
    </div>
    <div class="form-group">
     <%= f.label :price %><br />
     <%= f.text_field :price , class:'form-control'%><br />
    </div>

     <div class="form-group">
     <%= f.label :buy %><br />
     <%= f.text_field :buy , class:'form-control'%><br />
    </div>
    
    <%= f.submit "Submit" , class:'btn btn-primary'%>
    <%= link_to "Cancel" , books_path , class:'btn btn-default'%>
<% end %>
<%gfhdsDSCDSCDSCDSfdsfdfdeed

app/views/books/show.html.erb
  <div class='showimg'>
<div id='books-show'>
  <h2>Ruby on Rails power</h2>
     <ul>
    <%= image_tag('ruby_on_rails_power.jpg') %>
  </div>
  <div class="books-show-right">
    <h3>Book Info:</h3>
      <li><strong>Category :</strong>Ruby on rails</li>
      <li><strong>Authour :</strong>Aneesha Bakharia</li>
      <li><strong>Publisher :</strong>Course technology</li>
             <li><strong>Year :</strong>2007</li>
      <li><strong>ISBN:</strong>1598632167</li>
      <li><strong>Formate:</strong>paperback</li>
      <li><strong>Pages:</strong>678</li>
     </ul>
     <%=link_to "Buy For $5.47" , 'https://www.ebay.com/itm/144038903580?epid=50789121&hash=item2189633f1c:g:~eUAAOSwcbhf~f31&amdata=enc%3AAQAIAAAAwAyZrQtvzeSs6Few5IbrlCia0BaoPNpm0x%2FcO3%2F%2FaJHV32qDodgFDx6Fen%2FyCE%2FfvN8V%2Bq0OHnSw9a9HfIezi5ZG8oqDMgKC5Y3J9b1qL2j3o%2B36a8i4G1jbXUAVH52kqPaPgmWV5urlKPeH%2FP5lb7ZiElngp5YbHYkKbjX6T6bhWKOeDIFvLJqI6wdnESVPWMcxyXd%2F%2F3apz2W%2BAw5avOphCUDyCWsgpdwR5VV1yWXbvIdm7bMyFJ1HncE%2B7L80yA%3D%3D%7Ctkp%3ABk9SR7j_poiUYw' , class:'btn btn-success' , target:'_blank'%>
  </div>
  <div class="clearfix">
   <h4>Excerpt</h4>
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam venenatis porta nunc, eget imperdiet diam accumsan facilisis. Aenean dignissim sollicitudin finibus. Praesent pretium eleifend mauris, ac malesuada lectus pretium vel. Donec ut scelerisque risus. Pellentesque sagittis purus magna, ac sodales orci aliquet ut. Donec fringilla condimentum justo, nec rhoncus nibh pretium sit amet. Mauris vehicula cursus leo non condimentum. Vestibulum malesuada vel sem sed aliquam. Donec sit amet iaculis nibh, ut maximus dolor. Pellentesque facilisis a justo in tristique. Etiam vitae magna sed nulla pretium interdum. Quisque vitae dapibus ex. Nulla finibus nisi eget lobortis placerat.
  </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome' %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to "Home", root_path %></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to "About", about_path %></li>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
             Add new
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "book", new_book_path, class: "dropdown-item" %></li>
              <li><%= link_to "category", new_category_path, class: "dropdown-item" %></li>
              <li><%= link_to "author", new_author_path, class: "dropdown-item" %></li>
              <li><%= link_to "publisher", new_publisher_path, class: "dropdown-item" %></li>
            </ul>
          </div>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
    </header>

    <section>
    <div class="container">
      <h1>The Bookstore <small><%= @page_title ? @page_title : 'Welcome' %></small>
      </h1>
    </div>
    </section>


    <section>
     <div class="container">
       <div class="row"> 
          <div class="col-md-8">
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar'%>
          </div>
       </div>
     </div>
    </section>

    <footer>
      <div class="container">
       <p>Copyright &copy: 2014 , All Rights Reversed
       </p>
      </div>
    </footer>

  </body>
</html>

app/views/partials/_sidebar.html.erb
<%# side bar for the about us page %>
<% if params[:controller] == 'about' %>
  <div class="well">
    <h3>Location Info</h3>
    <ul>
        <li>The Bookstore</li>
        <li>499 Massachusetts Ave, Unit 2</li>
        <li>Boston, Ma 02110</li>
        <li>Phone: (617) 555-5555</li>
        <li>Email: Support@thebookstore.com</li>
    </ul>
   
  </div>
<% end %>

<%# side bar for the bookstrore %>
 <% if params[:controller] == 'books' %>
<div class="list-group">
  <a href="#" class="list-group-item">Ruby on rails</a>
  <a href="#" class="list-group-item">PHP</a>
  <a href="#" class="list-group-item">HTML5</a>
</div>
<% end %>

<%# $$ params[:action] == 'index' ||
params[:action] =='show' %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Publishers#new</h1>
<p>Find me in app/views/publishers/new.html.erb</p>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>